# Generated by Django 5.1.5 on 2025-05-12 14:28

import colorfield.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPUTADOR', 'Computador'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('TABLET', 'Tablet'), ('MOVIL', 'Celular'), ('HP_PRODISPLAY_P201', 'HP ProDisplay P201'), ('PORTATIL', 'Portátil'), ('TODO_EN_UNO', 'Todo en uno')], max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('BODEGA_CN', 'Bodega CN'), ('BODEGA', 'Bodega'), ('MALA', 'Mala'), ('MALO', 'Malo'), ('PENDIENTE_BAJA', 'Pendiente/Baja'), ('PERDIDO_ROBADO', 'Perdido/Robado'), ('REPARAR', 'Reparar'), ('REPARAR_BAJA', 'Reparar/Baja'), ('SEDE', 'Sede'), ('STOCK', 'Stock')], max_length=18, null=True)),
                ('marca', models.CharField(choices=[('DELL', 'Dell'), ('HP', 'HP'), ('LENOVO', 'Lenovo'), ('APPLE', 'Apple'), ('SAMSUNG', 'Samsung')], db_index=True, max_length=20)),
                ('regimen', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(blank=True, choices=[('ECCC', 'ECCC'), ('ECOL', 'ECOL'), ('CNC', 'CNC'), ('BODEGA_CN', 'Bodega CN'), ('COMPRADO', 'Comprado'), ('PROPIO', 'Propio')], max_length=100, null=True)),
                ('modelo', models.CharField(db_index=True, max_length=50)),
                ('serial', models.CharField(db_index=True, max_length=50, unique=True)),
                ('placa_cu', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_propiedad', models.CharField(blank=True, choices=[('PROPIO', 'Propio'), ('ARRENDADO', 'Arrendado'), ('DONADO', 'Donado'), ('OTRO', 'Otro')], max_length=10, null=True)),
                ('capacidad_disco_duro', models.CharField(blank=True, choices=[('120GB', '120 GB'), ('250GB', '250 GB'), ('500GB', '500 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB'), ('8TB', '8 TB')], max_length=10, null=True)),
                ('capacidad_memoria_ram', models.CharField(blank=True, choices=[('2GB', '2 GB'), ('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB')], max_length=10, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('CLIENTE', 'Cliente'), ('SEDE', 'Sede'), ('OTRO', 'Otro')], max_length=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_operativo', models.CharField(blank=True, choices=[('NA', 'No Aplica'), ('SERVER', 'Server'), ('WIN10', 'Windows 10'), ('WIN11', 'Windows 11'), ('WIN7', 'Windows 7'), ('VACIO', 'Sin Sistema Operativo'), ('MACOS', 'MacOS')], max_length=20, null=True)),
                ('procesador', models.CharField(blank=True, choices=[('AMD_A12', 'AMD A12'), ('AMD_A8_5500B', 'AMD A8-5500B APU'), ('AMD_RYZEN', 'AMD RYZEN'), ('AMD_RYZEN_3_2200GE', 'AMD Ryzen 3 2200GE'), ('I3_6200U', 'Intel Core i3 6200U'), ('I5_4430S', 'Intel Core i5 4430s'), ('I5_4460', 'Intel Core i5 4460'), ('I5_4590', 'Intel Core i5 4590'), ('I5_4600', 'Intel Core i5 4600'), ('I5_4670', 'Intel Core i5 4670'), ('I5_4750', 'Intel Core i5 4750'), ('I5_6500', 'Intel Core i5 6500'), ('I5_6500T', 'Intel Core i5 6500T'), ('I5_7500', 'Intel Core i5 7500'), ('I5_8400T', 'Intel Core i5 8400T'), ('I5_8500', 'Intel Core i5 8500'), ('I5_10TH', 'Intel Core i5 10th Gen'), ('I5_11TH', 'Intel Core i5 11th Gen'), ('I5_12TH', 'Intel Core i5 12th Gen'), ('I7_8TH', 'Intel Core i7 8th Gen'), ('I7_12TH', 'Intel Core i7 12th Gen'), ('I7_13TH', 'Intel Core i7 13th Gen'), ('I7_7TH', 'Intel Core i7 7th Gen'), ('I7_8565U', 'Intel Core i7 8565U @ 1.80GHz')], max_length=100, null=True)),
                ('estado_uso', models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('INHABILITADO', 'Inhabilitado')], max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones adicionales')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador')], default='admin', max_length=15)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre completo')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de celular inválido', regex='^\\+?\\d{7,15}$')], verbose_name='Celular')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Documento de identificación')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission')),
                ('sedes', models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='dispositivos.sede')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación de dispositivo'), ('MODIFICACION', 'Modificación de datos'), ('MOVIMIENTO', 'Movimiento registrado'), ('LOGIN', 'Inicio de sesión'), ('OTRO', 'Otro'), ('ELIMINACION', 'Eliminación')], default='OTRO', max_length=20)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('instancia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sede_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dispositivos.dispositivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inactivo', 'Inactivo')], default='disponible', max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fila', models.IntegerField()),
                ('columna', models.CharField(max_length=5)),
                ('color', models.CharField(default='#FFFFFF', max_length=20)),
                ('colorFuente', models.CharField(default='#000000', max_length=20)),
                ('colorOriginal', models.CharField(blank=True, max_length=50, null=True)),
                ('borde', models.BooleanField(default=True)),
                ('bordeDoble', models.BooleanField(default=False)),
                ('bordeDetalle', models.JSONField(default=dict)),
                ('piso', models.CharField(max_length=50)),
                ('mergedCells', models.JSONField(default=list)),
                ('dispositivos', models.ManyToManyField(blank=True, related_name='posiciones', to='dispositivos.dispositivo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='dispositivos.sede')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_relacionados', to='dispositivos.posicion'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='dispositivos.sede'),
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_analitico', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('sedes', models.ManyToManyField(related_name='servicios', to='dispositivos.sede')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='posicion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='dispositivos.servicios'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_origen', models.CharField(blank=True, choices=[('BODEGA', 'Bodega'), ('SEDE', 'Sede'), ('REPARACION', 'Reparación'), ('BAJA', 'Baja'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('ubicacion_destino', models.CharField(blank=True, choices=[('BODEGA', 'Bodega'), ('SEDE', 'Sede'), ('REPARACION', 'Reparación'), ('BAJA', 'Baja'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dispositivos.dispositivo')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('posicion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='dispositivos.posicion')),
                ('posicion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='dispositivos.posicion')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.sede')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['fecha_movimiento'], name='dispositivo_fecha_m_cab493_idx'), models.Index(fields=['dispositivo'], name='dispositivo_disposi_b3c7f4_idx'), models.Index(fields=['encargado'], name='dispositivo_encarga_d0e3e1_idx')],
            },
        ),
    ]
