# Generated by Django 5.1.5 on 2025-05-15 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicios', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='placa_cu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='piso',
            field=models.CharField(choices=[('P1', 'PISO1'), ('P2', 'PISO2'), ('P3', 'PISO3'), ('P4', 'PISO4'), ('T1', 'TORRE1')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roluser',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Documento de identificación'),
        ),
        migrations.AlterField(
            model_name='roluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='codigo_analitico',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioexterno',
            name='documento',
            field=models.CharField(help_text='Número de documento de identidad', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='asignaciondispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'VIGENTE')), fields=('usuario', 'dispositivo'), name='unique_vigente_usuario_dispositivo'),
        ),
    ]
