# Generated by Django 5.1.5 on 2025-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='dispositivos',
            field=models.ManyToManyField(blank=True, related_name='posiciones', to='dispositivos.dispositivo'),
        ),
    ]
