# Generated by Django 5.1.5 on 2025-03-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='columna',
        ),
        migrations.AddField(
            model_name='posicion',
            name='column',
            field=models.CharField(default='A', max_length=30),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='dispositivos',
            field=models.ManyToManyField(related_name='positiones', to='dispositivos.dispositivo'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inactivo', 'Inactivo')], default='disponible', max_length=80),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positiones', to='dispositivos.sede'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positiones', to='dispositivos.servicios'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
