# Generated by Django 5.1.5 on 2025-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alter_servicios_options_alter_dispositivo_placa_cu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='piso',
            field=models.CharField(choices=[('PISO1', 'P1'), ('PISO2', 'P2'), ('PISO3', 'P3'), ('PISO4', 'P4'), ('TORRE1', 'T1')], max_length=50),
        ),
    ]
