# Generated by Django 5.1.5 on 2025-03-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_remove_posicion_columna_posicion_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='column',
        ),
        migrations.AddField(
            model_name='posicion',
            name='columna',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posicion',
            name='dispositivos',
            field=models.ManyToManyField(related_name='posiciones', to='dispositivos.dispositivo'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inactivo', 'Inactivo')], default='disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='dispositivos.sede'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='dispositivos.servicios'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
