# Generated by Django 5.1.5 on 2025-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_posicion_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='capacidad_disco_duro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='capacidad_memoria_ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
