# Generated by Django 5.1.7 on 2025-03-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_remove_posicion_column_posicion_columna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='servicio',
        ),
    ]
