# Generated by Django 5.1.5 on 2025-04-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_remove_dispositivo_disponible_dispositivo_estado_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='usuario_asignado',
        ),
    ]
