# Generated by Django 5.1.5 on 2025-04-07 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_remove_dispositivo_usuario_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='estado_uso',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
