# Generated by Django 5.1.5 on 2025-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_remove_dispositivo_estado_uso_dispositivo_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='disponible',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('INHABILITADO', 'Inhabilitado')], default='DISPONIBLE', help_text='Indica si el dispositivo está disponible, en uso o inhabilitado', max_length=15),
        ),
    ]
