# Generated by Django 5.1.5 on 2025-04-11 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0006_alter_dispositivo_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha_modificacion']},
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='tipo_disco_duro',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='tipo_memoria_ram',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='usuario_asignado',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado_uso',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('INHABILITADO', 'Inhabilitado')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='historial',
            name='instancia_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='modelo_afectado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='sede_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('BODEGA_CN', 'Bodega CN'), ('BODEGA', 'Bodega'), ('MALA', 'Mala'), ('MALO', 'Malo'), ('PENDIENTE_BAJA', 'Pendiente/Baja'), ('PERDIDO_ROBADO', 'Perdido/Robado'), ('REPARAR', 'Reparar'), ('REPARAR_BAJA', 'Reparar/Baja'), ('SEDE', 'Sede'), ('STOCK', 'Stock')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='procesador',
            field=models.CharField(blank=True, choices=[('AMD_A12', 'AMD A12'), ('AMD_A8_5500B', 'AMD A8-5500B APU'), ('AMD_RYZEN', 'AMD RYZEN'), ('AMD_RYZEN_3_2200GE', 'AMD Ryzen 3 2200GE'), ('I3_6200U', 'Intel Core i3 6200U'), ('I5_4430S', 'Intel Core i5 4430s'), ('I5_4460', 'Intel Core i5 4460'), ('I5_4590', 'Intel Core i5 4590'), ('I5_4600', 'Intel Core i5 4600'), ('I5_4670', 'Intel Core i5 4670'), ('I5_4750', 'Intel Core i5 4750'), ('I5_6500', 'Intel Core i5 6500'), ('I5_6500T', 'Intel Core i5 6500T'), ('I5_7500', 'Intel Core i5 7500'), ('I5_8400T', 'Intel Core i5 8400T'), ('I5_8500', 'Intel Core i5 8500'), ('I5_10TH', 'Intel Core i5 10th Gen'), ('I5_11TH', 'Intel Core i5 11th Gen'), ('I5_12TH', 'Intel Core i5 12th Gen'), ('I7_8TH', 'Intel Core i7 8th Gen'), ('I7_12TH', 'Intel Core i7 12th Gen'), ('I7_13TH', 'Intel Core i7 13th Gen'), ('I7_7TH', 'Intel Core i7 7th Gen'), ('I7_8565U', 'Intel Core i7 8565U @ 1.80GHz')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='razon_social',
            field=models.CharField(blank=True, choices=[('ECCC', 'ECCC'), ('ECOL', 'ECOL'), ('CNC', 'CNC'), ('BODEGA_CN', 'Bodega CN'), ('COMPRADO', 'Comprado'), ('PROPIO', 'Propio')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='regimen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('TABLET', 'Tablet'), ('MOVIL', 'Celular'), ('HP_PRODISPLAY_P201', 'HP ProDisplay P201'), ('PORTATIL', 'Portátil'), ('TODO_EN_UNO', 'Todo en uno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historial',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dispositivos.dispositivo'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación de dispositivo'), ('MODIFICACION', 'Modificación de datos'), ('ASIGNACION', 'Cambio de usuario asignado'), ('MOVIMIENTO', 'Movimiento registrado'), ('LOGIN', 'Inicio de sesión'), ('OTRO', 'Otro'), ('ELIMINACION', 'Eliminación')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='dispositivos',
            field=models.ManyToManyField(related_name='posiciones', to='dispositivos.dispositivo'),
        ),
        migrations.AlterField(
            model_name='roluser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador')], default='admin', max_length=15),
        ),
    ]
