# Generated by Django 5.1.5 on 2025-04-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0007_alter_historial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_movimiento'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='dispositivos.sede'),
        ),
    ]
