# Generated by Django 5.1.5 on 2025-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0008_alter_movimiento_options_movimiento_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación de dispositivo'), ('MODIFICACION', 'Modificación de datos'), ('MOVIMIENTO', 'Movimiento registrado'), ('LOGIN', 'Inicio de sesión'), ('OTRO', 'Otro'), ('ELIMINACION', 'Eliminación')], default='OTRO', max_length=20),
        ),
    ]
