# Generated by Django 5.1.5 on 2025-04-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0009_alter_historial_tipo_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='ubicacion_destino',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='ubicacion_origen',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='posicion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='dispositivos.posicion'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='posicion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='dispositivos.posicion'),
        ),
    ]
