# Generated by Django 5.1.5 on 2025-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0010_remove_movimiento_ubicacion_destino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
        migrations.AlterModelOptions(
            name='posicion',
            options={'verbose_name': 'Posición', 'verbose_name_plural': 'Posiciones'},
        ),
        migrations.AlterField(
            model_name='posicion',
            name='dispositivos',
            field=models.ManyToManyField(blank=True, related_name='posiciones', to='dispositivos.dispositivo'),
        ),
    ]
