# Generated by Django 5.1.5 on 2025-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0011_alter_dispositivo_options_alter_historial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='codigo_analitico',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
