# Generated by Django 5.1.5 on 2025-05-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0012_alter_servicios_codigo_analitico'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_destino',
            field=models.CharField(blank=True, choices=[('BODEGA', 'Bodega'), ('SEDE', 'Sede'), ('REPARACION', 'Reparación'), ('BAJA', 'Baja'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_origen',
            field=models.CharField(blank=True, choices=[('BODEGA', 'Bodega'), ('SEDE', 'Sede'), ('REPARACION', 'Reparación'), ('BAJA', 'Baja'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='observacion',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='dispositivos.posicion'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='posicion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='dispositivos.posicion'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.sede'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha_movimiento'], name='dispositivo_fecha_m_cab493_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['dispositivo'], name='dispositivo_disposi_b3c7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['encargado'], name='dispositivo_encarga_d0e3e1_idx'),
        ),
    ]
